_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: f1f623f6-6f90-4f49-a6f9-51ba985bec7c
name: build-tools-5399
mail: greg+ci-terminus-build-tools@pantheon.io
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
